name 'nginx'
maintainer 'Alex Terrazas'
maintainer_email 'aterrazas76@live.com'
license 'all_rights'
description 'Installs/Configures nginx'
long_description 'Installs/Configures nginx'
version '0.1.0'
depends 'apt'
depends 'yum-epel'
